# Generated by Django 4.2.7 on 2025-09-24 17:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='compliance_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('extracted_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('partial', 'Partial'), ('fail', 'Fail')], default='fail', max_length=10)),
                ('fields_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('rupee', 'Rupee'), ('package', 'Package'), ('building', 'Building'), ('globe', 'Globe'), ('calendar', 'Calendar')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected', models.BooleanField(default=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('compliance_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_fields', to='compliance.compliancecheck')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancefield')),
            ],
            options={
                'unique_together': {('compliance_check', 'field')},
            },
        ),
    ]
